// <auto-generated />
using System;
using DijitaruVatigoSha.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DijitaruVatigoSha.Migrations
{
    [DbContext(typeof(DijitaruVatigoShaContext))]
    [Migration("20230717185154_All")]
    partial class All
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DijitaruVatigoSha.Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CollaboratorRole")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<int>("Modality")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId1");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("DijitaruVatigoSha.Models.PendingHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproverId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CollaboratorId")
                        .HasColumnType("int");

                    b.Property<int>("HourAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("PendingHours");
                });

            modelBuilder.Entity("DijitaruVatigoSha.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DijitaruVatigoSha.Models.Collaborator", b =>
                {
                    b.HasOne("DijitaruVatigoSha.Models.Project", null)
                        .WithMany("Approvers")
                        .HasForeignKey("ProjectId");

                    b.HasOne("DijitaruVatigoSha.Models.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId1");
                });

            modelBuilder.Entity("DijitaruVatigoSha.Models.PendingHour", b =>
                {
                    b.HasOne("DijitaruVatigoSha.Models.Collaborator", "Approver")
                        .WithMany("ApprovedHours")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DijitaruVatigoSha.Models.Collaborator", "Collaborator")
                        .WithMany("PendingHours")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DijitaruVatigoSha.Models.Project", "Project")
                        .WithMany("PendingHours")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Collaborator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DijitaruVatigoSha.Models.Collaborator", b =>
                {
                    b.Navigation("ApprovedHours");

                    b.Navigation("PendingHours");
                });

            modelBuilder.Entity("DijitaruVatigoSha.Models.Project", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Collaborators");

                    b.Navigation("PendingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
